project:
  type: book

metadata-files:
  - other/metadata.yml
  - other/glossar.yml

book:
  title: "zkYes Research"
  author: "Alexander Zammit"
  date: "03.08.2024"
  search: true
  repo-url: "https://github.com/kaxxa123/zkyes-research.git"
  issued: "03.08.2024"
  language: "en-US"
  isbn: ""
  image: "other/image.jpg"
  downloads: [pdf, epub]
  page-navigation: true
  chapters:
    - index.qmd
    - content/intro.qmd
    - content/early_tallying.qmd
    - content/receipt_freeness.qmd
    - content/onchain_tallying.qmd
    - content/voter_eligibility.qmd
    - content/voting_preferences.qmd
    - content/chain_choice.qmd
    - content/dapps.qmd
    - content/dao_private_voting.qmd
    - content/references.qmd
bibliography: other/references.bib
csl: other/ieee.csl

format:
  html:
    theme: cosmo
  pdf:
    keep-tex: true
    documentclass: scrreprt
    papersize: a4
    fontsize: 12pt
    geometry:
      - inner=3cm
      - outer=4cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \areaset{14cm}{22cm}
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
           showspaces = false,
           showtabs = false,
           breaksymbolleft={},
           breaklines
        }
    fig-pos: 'H'
  epub:
    toc: true
    lang: en-US
  docx:
    toc: false
    lang: en-US
